package javaee.msg.entity;

import lombok.Data;
import lombok.experimental.Accessors;

import java.util.Date;

@Data
@Accessors(chain = true)
public class Msg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.id
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.nickname
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.qq
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.email
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private String email;
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.reply_id
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.creat_time
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.id
     *
     * @return the value of msg.id
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.id
//     *
//     * @param id the value for msg.id
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.nickname
//     *
//     * @return the value of msg.nickname
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public String getNickname() {
//        return nickname;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.nickname
//     *
//     * @param nickname the value for msg.nickname
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setNickname(String nickname) {
//        this.nickname = nickname == null ? null : nickname.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.qq
//     *
//     * @return the value of msg.qq
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public String getQq() {
//        return qq;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.qq
//     *
//     * @param qq the value for msg.qq
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setQq(String qq) {
//        this.qq = qq == null ? null : qq.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.email
//     *
//     * @return the value of msg.email
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public String getEmail() {
//        return email;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.email
//     *
//     * @param email the value for msg.email
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setEmail(String email) {
//        this.email = email == null ? null : email.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.reply_id
//     *
//     * @return the value of msg.reply_id
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public String getReplyId() {
//        return replyId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.reply_id
//     *
//     * @param replyId the value for msg.reply_id
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setReplyId(String replyId) {
//        this.replyId = replyId == null ? null : replyId.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.creat_time
//     *
//     * @return the value of msg.creat_time
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public String getCreatTime() {
//        return creatTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.creat_time
//     *
//     * @param creatTime the value for msg.creat_time
//     *
//     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
//     */
//    public void setCreatTime(String creatTime) {
//        this.creatTime = creatTime == null ? null : creatTime.trim();
//    }
}