package javaee.msg.mapper;

import java.util.List;
import javaee.msg.entity.User;
//import javaee.msg.entity.UserWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    int deleteByPrimaryKey(@Param("host") String host, @Param("user") String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    //UserWithBLOBs selectByPrimaryKey(@Param("host") String host, @Param("user") String user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Tue Nov 26 18:34:36 CST 2024
     */
    int updateByPrimaryKey(User row);
    @Select("select * from user where name = #{name} and password = #{password}")
    User login(@Param("name") String name,@Param("password") String password);
}