package xju.ssm_msg.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;
import org.springframework.web.bind.annotation.ResponseBody;
import xju.ssm_msg.entity.Msg;
@Repository
public interface MsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    int insert(Msg row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    List<Msg> selectAll();
}