package xju.ssm_msg.entity;

import lombok.Data;

@Data
public class Msg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.id
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.nickname
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.qq
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.email
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.text
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.reply_id
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msg.create_time
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msg.id
     *
     * @return the value of msg.id
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
//    public Integer getId() {
//        return id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.id
//     *
//     * @param id the value for msg.id
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setId(Integer id) {
//        this.id = id;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.nickname
//     *
//     * @return the value of msg.nickname
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getNickname() {
//        return nickname;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.nickname
//     *
//     * @param nickname the value for msg.nickname
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setNickname(String nickname) {
//        this.nickname = nickname == null ? null : nickname.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.qq
//     *
//     * @return the value of msg.qq
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getQq() {
//        return qq;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.qq
//     *
//     * @param qq the value for msg.qq
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setQq(String qq) {
//        this.qq = qq == null ? null : qq.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.email
//     *
//     * @return the value of msg.email
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getEmail() {
//        return email;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.email
//     *
//     * @param email the value for msg.email
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setEmail(String email) {
//        this.email = email == null ? null : email.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.text
//     *
//     * @return the value of msg.text
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getText() {
//        return text;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.text
//     *
//     * @param text the value for msg.text
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setText(String text) {
//        this.text = text == null ? null : text.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.reply_id
//     *
//     * @return the value of msg.reply_id
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getReplyId() {
//        return replyId;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.reply_id
//     *
//     * @param replyId the value for msg.reply_id
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setReplyId(String replyId) {
//        this.replyId = replyId == null ? null : replyId.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column msg.create_time
//     *
//     * @return the value of msg.create_time
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public String getCreateTime() {
//        return createTime;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column msg.create_time
//     *
//     * @param createTime the value for msg.create_time
//     *
//     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
//     */
//    public void setCreateTime(String createTime) {
//        this.createTime = createTime == null ? null : createTime.trim();
//    }
}