package xju.ssm_msg.entity;

import lombok.Data;

import java.util.Date;
@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Host
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String host;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Select_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String selectPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Insert_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String insertPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Update_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String updatePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Delete_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String deletePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Drop_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String dropPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Reload_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String reloadPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Shutdown_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String shutdownPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Process_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String processPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.File_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String filePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Grant_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String grantPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.References_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String referencesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Index_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String indexPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String alterPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_db_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String showDbPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Super_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String superPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tmp_table_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createTmpTablePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Lock_tables_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String lockTablesPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Execute_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String executePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_slave_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String replSlavePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_client_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String replClientPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_view_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_view_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String showViewPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_routine_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_routine_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String alterRoutinePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_user_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createUserPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Event_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String eventPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Trigger_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String triggerPriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tablespace_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createTablespacePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_type
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String sslType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_questions
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Integer maxQuestions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_updates
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Integer maxUpdates;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_connections
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Integer maxConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_user_connections
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Integer maxUserConnections;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.plugin
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String plugin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_expired
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String passwordExpired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_last_changed
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Date passwordLastChanged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_lifetime
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Short passwordLifetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account_locked
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String accountLocked;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_role_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String createRolePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Drop_role_priv
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String dropRolePriv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_reuse_history
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Short passwordReuseHistory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_reuse_time
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private Short passwordReuseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password_require_current
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String passwordRequireCurrent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_cipher
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private byte[] sslCipher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_issuer
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private byte[] x509Issuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.x509_subject
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private byte[] x509Subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.authentication_string
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String authenticationString;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.User_attributes
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
    private String userAttributes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Host
     *
     * @return the value of user.Host
     *
     * @mbg.generated Fri Nov 29 01:44:43 CST 2024
     */
//
}